// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
	models "github.com/yoshioka0101/ai_plan_chat/gen/models"
)

type AiInterpretationMod interface {
	Apply(context.Context, *AiInterpretationTemplate)
}

type AiInterpretationModFunc func(context.Context, *AiInterpretationTemplate)

func (f AiInterpretationModFunc) Apply(ctx context.Context, n *AiInterpretationTemplate) {
	f(ctx, n)
}

type AiInterpretationModSlice []AiInterpretationMod

func (mods AiInterpretationModSlice) Apply(ctx context.Context, n *AiInterpretationTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// AiInterpretationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type AiInterpretationTemplate struct {
	ID                 func() string
	UserID             func() string
	InputText          func() string
	StructuredResult   func() types.JSON[json.RawMessage]
	OriginalResult     func() null.Val[types.JSON[json.RawMessage]]
	AiModel            func() string
	AiPromptTokens     func() null.Val[int32]
	AiCompletionTokens func() null.Val[int32]
	CreatedAt          func() time.Time

	r aiInterpretationR
	f *Factory

	alreadyPersisted bool
}

type aiInterpretationR struct {
	User                              *aiInterpretationRUserR
	InterpretationInterpretationItems []*aiInterpretationRInterpretationInterpretationItemsR
	Tasks                             []*aiInterpretationRTasksR
}

type aiInterpretationRUserR struct {
	o *UserTemplate
}
type aiInterpretationRInterpretationInterpretationItemsR struct {
	number int
	o      *InterpretationItemTemplate
}
type aiInterpretationRTasksR struct {
	number int
	o      *TaskTemplate
}

// Apply mods to the AiInterpretationTemplate
func (o *AiInterpretationTemplate) Apply(ctx context.Context, mods ...AiInterpretationMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.AiInterpretation
// according to the relationships in the template. Nothing is inserted into the db
func (t AiInterpretationTemplate) setModelRels(o *models.AiInterpretation) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.AiInterpretations = append(rel.R.AiInterpretations, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}

	if t.r.InterpretationInterpretationItems != nil {
		rel := models.InterpretationItemSlice{}
		for _, r := range t.r.InterpretationInterpretationItems {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.InterpretationID = o.ID // h2
				rel.R.InterpretationAiInterpretation = o
			}
			rel = append(rel, related...)
		}
		o.R.InterpretationInterpretationItems = rel
	}

	if t.r.Tasks != nil {
		rel := models.TaskSlice{}
		for _, r := range t.r.Tasks {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.AiInterpretationID = null.From(o.ID) // h2
				rel.R.AiInterpretation = o
			}
			rel = append(rel, related...)
		}
		o.R.Tasks = rel
	}
}

// BuildSetter returns an *models.AiInterpretationSetter
// this does nothing with the relationship templates
func (o AiInterpretationTemplate) BuildSetter() *models.AiInterpretationSetter {
	m := &models.AiInterpretationSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.InputText != nil {
		val := o.InputText()
		m.InputText = omit.From(val)
	}
	if o.StructuredResult != nil {
		val := o.StructuredResult()
		m.StructuredResult = omit.From(val)
	}
	if o.OriginalResult != nil {
		val := o.OriginalResult()
		m.OriginalResult = omitnull.FromNull(val)
	}
	if o.AiModel != nil {
		val := o.AiModel()
		m.AiModel = omit.From(val)
	}
	if o.AiPromptTokens != nil {
		val := o.AiPromptTokens()
		m.AiPromptTokens = omitnull.FromNull(val)
	}
	if o.AiCompletionTokens != nil {
		val := o.AiCompletionTokens()
		m.AiCompletionTokens = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.AiInterpretationSetter
// this does nothing with the relationship templates
func (o AiInterpretationTemplate) BuildManySetter(number int) []*models.AiInterpretationSetter {
	m := make([]*models.AiInterpretationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.AiInterpretation
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AiInterpretationTemplate.Create
func (o AiInterpretationTemplate) Build() *models.AiInterpretation {
	m := &models.AiInterpretation{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.InputText != nil {
		m.InputText = o.InputText()
	}
	if o.StructuredResult != nil {
		m.StructuredResult = o.StructuredResult()
	}
	if o.OriginalResult != nil {
		m.OriginalResult = o.OriginalResult()
	}
	if o.AiModel != nil {
		m.AiModel = o.AiModel()
	}
	if o.AiPromptTokens != nil {
		m.AiPromptTokens = o.AiPromptTokens()
	}
	if o.AiCompletionTokens != nil {
		m.AiCompletionTokens = o.AiCompletionTokens()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.AiInterpretationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AiInterpretationTemplate.CreateMany
func (o AiInterpretationTemplate) BuildMany(number int) models.AiInterpretationSlice {
	m := make(models.AiInterpretationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAiInterpretation(m *models.AiInterpretationSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "36")
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil, "36")
		m.UserID = omit.From(val)
	}
	if !(m.InputText.IsValue()) {
		val := random_string(nil)
		m.InputText = omit.From(val)
	}
	if !(m.StructuredResult.IsValue()) {
		val := random_types_JSON_json_RawMessage_(nil)
		m.StructuredResult = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.AiInterpretation
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *AiInterpretationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.AiInterpretation) error {
	var err error

	isInterpretationInterpretationItemsDone, _ := aiInterpretationRelInterpretationInterpretationItemsCtx.Value(ctx)
	if !isInterpretationInterpretationItemsDone && o.r.InterpretationInterpretationItems != nil {
		ctx = aiInterpretationRelInterpretationInterpretationItemsCtx.WithValue(ctx, true)
		for _, r := range o.r.InterpretationInterpretationItems {
			if r.o.alreadyPersisted {
				m.R.InterpretationInterpretationItems = append(m.R.InterpretationInterpretationItems, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachInterpretationInterpretationItems(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isTasksDone, _ := aiInterpretationRelTasksCtx.Value(ctx)
	if !isTasksDone && o.r.Tasks != nil {
		ctx = aiInterpretationRelTasksCtx.WithValue(ctx, true)
		for _, r := range o.r.Tasks {
			if r.o.alreadyPersisted {
				m.R.Tasks = append(m.R.Tasks, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachTasks(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a aiInterpretation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *AiInterpretationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.AiInterpretation, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAiInterpretation(opt)

	if o.r.User == nil {
		AiInterpretationMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.AiInterpretations.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a aiInterpretation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *AiInterpretationTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.AiInterpretation {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a aiInterpretation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *AiInterpretationTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.AiInterpretation {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple aiInterpretations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o AiInterpretationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.AiInterpretationSlice, error) {
	var err error
	m := make(models.AiInterpretationSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple aiInterpretations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o AiInterpretationTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.AiInterpretationSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple aiInterpretations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o AiInterpretationTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.AiInterpretationSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// AiInterpretation has methods that act as mods for the AiInterpretationTemplate
var AiInterpretationMods aiInterpretationMods

type aiInterpretationMods struct{}

func (m aiInterpretationMods) RandomizeAllColumns(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModSlice{
		AiInterpretationMods.RandomID(f),
		AiInterpretationMods.RandomUserID(f),
		AiInterpretationMods.RandomInputText(f),
		AiInterpretationMods.RandomStructuredResult(f),
		AiInterpretationMods.RandomOriginalResult(f),
		AiInterpretationMods.RandomAiModel(f),
		AiInterpretationMods.RandomAiPromptTokens(f),
		AiInterpretationMods.RandomAiCompletionTokens(f),
		AiInterpretationMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m aiInterpretationMods) ID(val string) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m aiInterpretationMods) IDFunc(f func() string) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m aiInterpretationMods) UnsetID() AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m aiInterpretationMods) RandomID(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.ID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m aiInterpretationMods) UserID(val string) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m aiInterpretationMods) UserIDFunc(f func() string) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m aiInterpretationMods) UnsetUserID() AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m aiInterpretationMods) RandomUserID(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.UserID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m aiInterpretationMods) InputText(val string) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.InputText = func() string { return val }
	})
}

// Set the Column from the function
func (m aiInterpretationMods) InputTextFunc(f func() string) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.InputText = f
	})
}

// Clear any values for the column
func (m aiInterpretationMods) UnsetInputText() AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.InputText = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m aiInterpretationMods) RandomInputText(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.InputText = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m aiInterpretationMods) StructuredResult(val types.JSON[json.RawMessage]) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.StructuredResult = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m aiInterpretationMods) StructuredResultFunc(f func() types.JSON[json.RawMessage]) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.StructuredResult = f
	})
}

// Clear any values for the column
func (m aiInterpretationMods) UnsetStructuredResult() AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.StructuredResult = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m aiInterpretationMods) RandomStructuredResult(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.StructuredResult = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m aiInterpretationMods) OriginalResult(val null.Val[types.JSON[json.RawMessage]]) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.OriginalResult = func() null.Val[types.JSON[json.RawMessage]] { return val }
	})
}

// Set the Column from the function
func (m aiInterpretationMods) OriginalResultFunc(f func() null.Val[types.JSON[json.RawMessage]]) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.OriginalResult = f
	})
}

// Clear any values for the column
func (m aiInterpretationMods) UnsetOriginalResult() AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.OriginalResult = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m aiInterpretationMods) RandomOriginalResult(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.OriginalResult = func() null.Val[types.JSON[json.RawMessage]] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_JSON_json_RawMessage_(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m aiInterpretationMods) RandomOriginalResultNotNull(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.OriginalResult = func() null.Val[types.JSON[json.RawMessage]] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_JSON_json_RawMessage_(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m aiInterpretationMods) AiModel(val string) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiModel = func() string { return val }
	})
}

// Set the Column from the function
func (m aiInterpretationMods) AiModelFunc(f func() string) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiModel = f
	})
}

// Clear any values for the column
func (m aiInterpretationMods) UnsetAiModel() AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiModel = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m aiInterpretationMods) RandomAiModel(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiModel = func() string {
			return random_string(f, "100")
		}
	})
}

// Set the model columns to this value
func (m aiInterpretationMods) AiPromptTokens(val null.Val[int32]) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiPromptTokens = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m aiInterpretationMods) AiPromptTokensFunc(f func() null.Val[int32]) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiPromptTokens = f
	})
}

// Clear any values for the column
func (m aiInterpretationMods) UnsetAiPromptTokens() AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiPromptTokens = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m aiInterpretationMods) RandomAiPromptTokens(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiPromptTokens = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m aiInterpretationMods) RandomAiPromptTokensNotNull(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiPromptTokens = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m aiInterpretationMods) AiCompletionTokens(val null.Val[int32]) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiCompletionTokens = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m aiInterpretationMods) AiCompletionTokensFunc(f func() null.Val[int32]) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiCompletionTokens = f
	})
}

// Clear any values for the column
func (m aiInterpretationMods) UnsetAiCompletionTokens() AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiCompletionTokens = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m aiInterpretationMods) RandomAiCompletionTokens(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiCompletionTokens = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m aiInterpretationMods) RandomAiCompletionTokensNotNull(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.AiCompletionTokens = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m aiInterpretationMods) CreatedAt(val time.Time) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m aiInterpretationMods) CreatedAtFunc(f func() time.Time) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m aiInterpretationMods) UnsetCreatedAt() AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m aiInterpretationMods) RandomCreatedAt(f *faker.Faker) AiInterpretationMod {
	return AiInterpretationModFunc(func(_ context.Context, o *AiInterpretationTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m aiInterpretationMods) WithParentsCascading() AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		if isDone, _ := aiInterpretationWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = aiInterpretationWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m aiInterpretationMods) WithUser(rel *UserTemplate) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		o.r.User = &aiInterpretationRUserR{
			o: rel,
		}
	})
}

func (m aiInterpretationMods) WithNewUser(mods ...UserMod) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m aiInterpretationMods) WithExistingUser(em *models.User) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		o.r.User = &aiInterpretationRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m aiInterpretationMods) WithoutUser() AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		o.r.User = nil
	})
}

func (m aiInterpretationMods) WithInterpretationInterpretationItems(number int, related *InterpretationItemTemplate) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		o.r.InterpretationInterpretationItems = []*aiInterpretationRInterpretationInterpretationItemsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m aiInterpretationMods) WithNewInterpretationInterpretationItems(number int, mods ...InterpretationItemMod) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		related := o.f.NewInterpretationItemWithContext(ctx, mods...)
		m.WithInterpretationInterpretationItems(number, related).Apply(ctx, o)
	})
}

func (m aiInterpretationMods) AddInterpretationInterpretationItems(number int, related *InterpretationItemTemplate) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		o.r.InterpretationInterpretationItems = append(o.r.InterpretationInterpretationItems, &aiInterpretationRInterpretationInterpretationItemsR{
			number: number,
			o:      related,
		})
	})
}

func (m aiInterpretationMods) AddNewInterpretationInterpretationItems(number int, mods ...InterpretationItemMod) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		related := o.f.NewInterpretationItemWithContext(ctx, mods...)
		m.AddInterpretationInterpretationItems(number, related).Apply(ctx, o)
	})
}

func (m aiInterpretationMods) AddExistingInterpretationInterpretationItems(existingModels ...*models.InterpretationItem) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		for _, em := range existingModels {
			o.r.InterpretationInterpretationItems = append(o.r.InterpretationInterpretationItems, &aiInterpretationRInterpretationInterpretationItemsR{
				o: o.f.FromExistingInterpretationItem(em),
			})
		}
	})
}

func (m aiInterpretationMods) WithoutInterpretationInterpretationItems() AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		o.r.InterpretationInterpretationItems = nil
	})
}

func (m aiInterpretationMods) WithTasks(number int, related *TaskTemplate) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		o.r.Tasks = []*aiInterpretationRTasksR{{
			number: number,
			o:      related,
		}}
	})
}

func (m aiInterpretationMods) WithNewTasks(number int, mods ...TaskMod) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		related := o.f.NewTaskWithContext(ctx, mods...)
		m.WithTasks(number, related).Apply(ctx, o)
	})
}

func (m aiInterpretationMods) AddTasks(number int, related *TaskTemplate) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		o.r.Tasks = append(o.r.Tasks, &aiInterpretationRTasksR{
			number: number,
			o:      related,
		})
	})
}

func (m aiInterpretationMods) AddNewTasks(number int, mods ...TaskMod) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		related := o.f.NewTaskWithContext(ctx, mods...)
		m.AddTasks(number, related).Apply(ctx, o)
	})
}

func (m aiInterpretationMods) AddExistingTasks(existingModels ...*models.Task) AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		for _, em := range existingModels {
			o.r.Tasks = append(o.r.Tasks, &aiInterpretationRTasksR{
				o: o.f.FromExistingTask(em),
			})
		}
	})
}

func (m aiInterpretationMods) WithoutTasks() AiInterpretationMod {
	return AiInterpretationModFunc(func(ctx context.Context, o *AiInterpretationTemplate) {
		o.r.Tasks = nil
	})
}
