// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for ai_interpretations
	aiInterpretationWithParentsCascadingCtx                 = newContextual[bool]("aiInterpretationWithParentsCascading")
	aiInterpretationRelUserCtx                              = newContextual[bool]("ai_interpretations.users.fk_ai_interpretations_user")
	aiInterpretationRelInterpretationInterpretationItemsCtx = newContextual[bool]("ai_interpretations.interpretation_items.fk_interpretation_items_interpretation")
	aiInterpretationRelTasksCtx                             = newContextual[bool]("ai_interpretations.tasks.fk_tasks_ai_interpretation")

	// Relationship Contexts for interpretation_items
	interpretationItemWithParentsCascadingCtx              = newContextual[bool]("interpretationItemWithParentsCascading")
	interpretationItemRelInterpretationAiInterpretationCtx = newContextual[bool]("ai_interpretations.interpretation_items.fk_interpretation_items_interpretation")

	// Relationship Contexts for tasks
	taskWithParentsCascadingCtx = newContextual[bool]("taskWithParentsCascading")
	taskRelAiInterpretationCtx  = newContextual[bool]("ai_interpretations.tasks.fk_tasks_ai_interpretation")
	taskRelUserCtx              = newContextual[bool]("tasks.users.fk_tasks_user")

	// Relationship Contexts for user_auths
	userAuthWithParentsCascadingCtx = newContextual[bool]("userAuthWithParentsCascading")
	userAuthRelUserCtx              = newContextual[bool]("user_auths.users.fk_user_auths_user")

	// Relationship Contexts for users
	userWithParentsCascadingCtx = newContextual[bool]("userWithParentsCascading")
	userRelAiInterpretationsCtx = newContextual[bool]("ai_interpretations.users.fk_ai_interpretations_user")
	userRelTasksCtx             = newContextual[bool]("tasks.users.fk_tasks_user")
	userRelUserAuthsCtx         = newContextual[bool]("user_auths.users.fk_user_auths_user")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
