// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/yoshioka0101/ai_plan_chat/models"
)

type Factory struct {
	baseTaskMods TaskModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewTask(mods ...TaskMod) *TaskTemplate {
	return f.NewTaskWithContext(context.Background(), mods...)
}

func (f *Factory) NewTaskWithContext(ctx context.Context, mods ...TaskMod) *TaskTemplate {
	o := &TaskTemplate{f: f}

	if f != nil {
		f.baseTaskMods.Apply(ctx, o)
	}

	TaskModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingTask(m *models.Task) *TaskTemplate {
	o := &TaskTemplate{f: f, alreadyPersisted: true}

	o.ID = func() string { return m.ID }
	o.Title = func() string { return m.Title }
	o.Description = func() null.Val[string] { return m.Description }
	o.DueAt = func() null.Val[time.Time] { return m.DueAt }
	o.Status = func() string { return m.Status }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) ClearBaseTaskMods() {
	f.baseTaskMods = nil
}

func (f *Factory) AddBaseTaskMod(mods ...TaskMod) {
	f.baseTaskMods = append(f.baseTaskMods, mods...)
}
