// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
	models "github.com/yoshioka0101/ai_plan_chat/gen/models"
)

type InterpretationItemMod interface {
	Apply(context.Context, *InterpretationItemTemplate)
}

type InterpretationItemModFunc func(context.Context, *InterpretationItemTemplate)

func (f InterpretationItemModFunc) Apply(ctx context.Context, n *InterpretationItemTemplate) {
	f(ctx, n)
}

type InterpretationItemModSlice []InterpretationItemMod

func (mods InterpretationItemModSlice) Apply(ctx context.Context, n *InterpretationItemTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// InterpretationItemTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type InterpretationItemTemplate struct {
	ID               func() string
	InterpretationID func() string
	ItemIndex        func() int32
	ResourceType     func() string
	ResourceID       func() null.Val[string]
	Status           func() string
	Data             func() types.JSON[json.RawMessage]
	OriginalData     func() types.JSON[json.RawMessage]
	ReviewedAt       func() null.Val[time.Time]
	CreatedAt        func() time.Time
	UpdatedAt        func() time.Time

	r interpretationItemR
	f *Factory

	alreadyPersisted bool
}

type interpretationItemR struct {
	InterpretationAiInterpretation *interpretationItemRInterpretationAiInterpretationR
}

type interpretationItemRInterpretationAiInterpretationR struct {
	o *AiInterpretationTemplate
}

// Apply mods to the InterpretationItemTemplate
func (o *InterpretationItemTemplate) Apply(ctx context.Context, mods ...InterpretationItemMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.InterpretationItem
// according to the relationships in the template. Nothing is inserted into the db
func (t InterpretationItemTemplate) setModelRels(o *models.InterpretationItem) {
	if t.r.InterpretationAiInterpretation != nil {
		rel := t.r.InterpretationAiInterpretation.o.Build()
		rel.R.InterpretationInterpretationItems = append(rel.R.InterpretationInterpretationItems, o)
		o.InterpretationID = rel.ID // h2
		o.R.InterpretationAiInterpretation = rel
	}
}

// BuildSetter returns an *models.InterpretationItemSetter
// this does nothing with the relationship templates
func (o InterpretationItemTemplate) BuildSetter() *models.InterpretationItemSetter {
	m := &models.InterpretationItemSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.InterpretationID != nil {
		val := o.InterpretationID()
		m.InterpretationID = omit.From(val)
	}
	if o.ItemIndex != nil {
		val := o.ItemIndex()
		m.ItemIndex = omit.From(val)
	}
	if o.ResourceType != nil {
		val := o.ResourceType()
		m.ResourceType = omit.From(val)
	}
	if o.ResourceID != nil {
		val := o.ResourceID()
		m.ResourceID = omitnull.FromNull(val)
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = omit.From(val)
	}
	if o.Data != nil {
		val := o.Data()
		m.Data = omit.From(val)
	}
	if o.OriginalData != nil {
		val := o.OriginalData()
		m.OriginalData = omit.From(val)
	}
	if o.ReviewedAt != nil {
		val := o.ReviewedAt()
		m.ReviewedAt = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.InterpretationItemSetter
// this does nothing with the relationship templates
func (o InterpretationItemTemplate) BuildManySetter(number int) []*models.InterpretationItemSetter {
	m := make([]*models.InterpretationItemSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.InterpretationItem
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use InterpretationItemTemplate.Create
func (o InterpretationItemTemplate) Build() *models.InterpretationItem {
	m := &models.InterpretationItem{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.InterpretationID != nil {
		m.InterpretationID = o.InterpretationID()
	}
	if o.ItemIndex != nil {
		m.ItemIndex = o.ItemIndex()
	}
	if o.ResourceType != nil {
		m.ResourceType = o.ResourceType()
	}
	if o.ResourceID != nil {
		m.ResourceID = o.ResourceID()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.Data != nil {
		m.Data = o.Data()
	}
	if o.OriginalData != nil {
		m.OriginalData = o.OriginalData()
	}
	if o.ReviewedAt != nil {
		m.ReviewedAt = o.ReviewedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.InterpretationItemSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use InterpretationItemTemplate.CreateMany
func (o InterpretationItemTemplate) BuildMany(number int) models.InterpretationItemSlice {
	m := make(models.InterpretationItemSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableInterpretationItem(m *models.InterpretationItemSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "36")
		m.ID = omit.From(val)
	}
	if !(m.InterpretationID.IsValue()) {
		val := random_string(nil, "36")
		m.InterpretationID = omit.From(val)
	}
	if !(m.ItemIndex.IsValue()) {
		val := random_int32(nil)
		m.ItemIndex = omit.From(val)
	}
	if !(m.ResourceType.IsValue()) {
		val := random_string(nil, "20")
		m.ResourceType = omit.From(val)
	}
	if !(m.Data.IsValue()) {
		val := random_types_JSON_json_RawMessage_(nil)
		m.Data = omit.From(val)
	}
	if !(m.OriginalData.IsValue()) {
		val := random_types_JSON_json_RawMessage_(nil)
		m.OriginalData = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.InterpretationItem
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *InterpretationItemTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.InterpretationItem) error {
	var err error

	return err
}

// Create builds a interpretationItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *InterpretationItemTemplate) Create(ctx context.Context, exec bob.Executor) (*models.InterpretationItem, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableInterpretationItem(opt)

	if o.r.InterpretationAiInterpretation == nil {
		InterpretationItemMods.WithNewInterpretationAiInterpretation().Apply(ctx, o)
	}

	var rel0 *models.AiInterpretation

	if o.r.InterpretationAiInterpretation.o.alreadyPersisted {
		rel0 = o.r.InterpretationAiInterpretation.o.Build()
	} else {
		rel0, err = o.r.InterpretationAiInterpretation.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.InterpretationID = omit.From(rel0.ID)

	m, err := models.InterpretationItems.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.InterpretationAiInterpretation = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a interpretationItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *InterpretationItemTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.InterpretationItem {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a interpretationItem and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *InterpretationItemTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.InterpretationItem {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple interpretationItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o InterpretationItemTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.InterpretationItemSlice, error) {
	var err error
	m := make(models.InterpretationItemSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple interpretationItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o InterpretationItemTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.InterpretationItemSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple interpretationItems and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o InterpretationItemTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.InterpretationItemSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// InterpretationItem has methods that act as mods for the InterpretationItemTemplate
var InterpretationItemMods interpretationItemMods

type interpretationItemMods struct{}

func (m interpretationItemMods) RandomizeAllColumns(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModSlice{
		InterpretationItemMods.RandomID(f),
		InterpretationItemMods.RandomInterpretationID(f),
		InterpretationItemMods.RandomItemIndex(f),
		InterpretationItemMods.RandomResourceType(f),
		InterpretationItemMods.RandomResourceID(f),
		InterpretationItemMods.RandomStatus(f),
		InterpretationItemMods.RandomData(f),
		InterpretationItemMods.RandomOriginalData(f),
		InterpretationItemMods.RandomReviewedAt(f),
		InterpretationItemMods.RandomCreatedAt(f),
		InterpretationItemMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m interpretationItemMods) ID(val string) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) IDFunc(f func() string) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetID() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m interpretationItemMods) RandomID(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) InterpretationID(val string) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.InterpretationID = func() string { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) InterpretationIDFunc(f func() string) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.InterpretationID = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetInterpretationID() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.InterpretationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m interpretationItemMods) RandomInterpretationID(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.InterpretationID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) ItemIndex(val int32) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ItemIndex = func() int32 { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) ItemIndexFunc(f func() int32) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ItemIndex = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetItemIndex() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ItemIndex = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m interpretationItemMods) RandomItemIndex(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ItemIndex = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) ResourceType(val string) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ResourceType = func() string { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) ResourceTypeFunc(f func() string) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ResourceType = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetResourceType() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ResourceType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m interpretationItemMods) RandomResourceType(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ResourceType = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) ResourceID(val null.Val[string]) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ResourceID = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) ResourceIDFunc(f func() null.Val[string]) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ResourceID = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetResourceID() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ResourceID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m interpretationItemMods) RandomResourceID(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ResourceID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "36")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m interpretationItemMods) RandomResourceIDNotNull(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ResourceID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "36")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) Status(val string) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) StatusFunc(f func() string) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetStatus() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m interpretationItemMods) RandomStatus(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.Status = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) Data(val types.JSON[json.RawMessage]) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.Data = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) DataFunc(f func() types.JSON[json.RawMessage]) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.Data = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetData() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.Data = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m interpretationItemMods) RandomData(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.Data = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) OriginalData(val types.JSON[json.RawMessage]) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.OriginalData = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) OriginalDataFunc(f func() types.JSON[json.RawMessage]) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.OriginalData = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetOriginalData() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.OriginalData = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m interpretationItemMods) RandomOriginalData(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.OriginalData = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) ReviewedAt(val null.Val[time.Time]) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ReviewedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) ReviewedAtFunc(f func() null.Val[time.Time]) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ReviewedAt = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetReviewedAt() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ReviewedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m interpretationItemMods) RandomReviewedAt(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ReviewedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m interpretationItemMods) RandomReviewedAtNotNull(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.ReviewedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) CreatedAt(val time.Time) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) CreatedAtFunc(f func() time.Time) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetCreatedAt() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m interpretationItemMods) RandomCreatedAt(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m interpretationItemMods) UpdatedAt(val time.Time) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m interpretationItemMods) UpdatedAtFunc(f func() time.Time) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m interpretationItemMods) UnsetUpdatedAt() InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m interpretationItemMods) RandomUpdatedAt(f *faker.Faker) InterpretationItemMod {
	return InterpretationItemModFunc(func(_ context.Context, o *InterpretationItemTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m interpretationItemMods) WithParentsCascading() InterpretationItemMod {
	return InterpretationItemModFunc(func(ctx context.Context, o *InterpretationItemTemplate) {
		if isDone, _ := interpretationItemWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = interpretationItemWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewAiInterpretationWithContext(ctx, AiInterpretationMods.WithParentsCascading())
			m.WithInterpretationAiInterpretation(related).Apply(ctx, o)
		}
	})
}

func (m interpretationItemMods) WithInterpretationAiInterpretation(rel *AiInterpretationTemplate) InterpretationItemMod {
	return InterpretationItemModFunc(func(ctx context.Context, o *InterpretationItemTemplate) {
		o.r.InterpretationAiInterpretation = &interpretationItemRInterpretationAiInterpretationR{
			o: rel,
		}
	})
}

func (m interpretationItemMods) WithNewInterpretationAiInterpretation(mods ...AiInterpretationMod) InterpretationItemMod {
	return InterpretationItemModFunc(func(ctx context.Context, o *InterpretationItemTemplate) {
		related := o.f.NewAiInterpretationWithContext(ctx, mods...)

		m.WithInterpretationAiInterpretation(related).Apply(ctx, o)
	})
}

func (m interpretationItemMods) WithExistingInterpretationAiInterpretation(em *models.AiInterpretation) InterpretationItemMod {
	return InterpretationItemModFunc(func(ctx context.Context, o *InterpretationItemTemplate) {
		o.r.InterpretationAiInterpretation = &interpretationItemRInterpretationAiInterpretationR{
			o: o.f.FromExistingAiInterpretation(em),
		}
	})
}

func (m interpretationItemMods) WithoutInterpretationAiInterpretation() InterpretationItemMod {
	return InterpretationItemModFunc(func(ctx context.Context, o *InterpretationItemTemplate) {
		o.r.InterpretationAiInterpretation = nil
	})
}
