// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "github.com/yoshioka0101/ai_plan_chat/gen/models"
)

type TaskMod interface {
	Apply(context.Context, *TaskTemplate)
}

type TaskModFunc func(context.Context, *TaskTemplate)

func (f TaskModFunc) Apply(ctx context.Context, n *TaskTemplate) {
	f(ctx, n)
}

type TaskModSlice []TaskMod

func (mods TaskModSlice) Apply(ctx context.Context, n *TaskTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// TaskTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type TaskTemplate struct {
	ID                 func() string
	UserID             func() string
	Title              func() string
	Description        func() null.Val[string]
	DueAt              func() null.Val[time.Time]
	Status             func() string
	Source             func() string
	AiInterpretationID func() null.Val[string]
	CreatedAt          func() time.Time
	UpdatedAt          func() time.Time

	r taskR
	f *Factory

	alreadyPersisted bool
}

type taskR struct {
	AiInterpretation *taskRAiInterpretationR
	User             *taskRUserR
}

type taskRAiInterpretationR struct {
	o *AiInterpretationTemplate
}
type taskRUserR struct {
	o *UserTemplate
}

// Apply mods to the TaskTemplate
func (o *TaskTemplate) Apply(ctx context.Context, mods ...TaskMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Task
// according to the relationships in the template. Nothing is inserted into the db
func (t TaskTemplate) setModelRels(o *models.Task) {
	if t.r.AiInterpretation != nil {
		rel := t.r.AiInterpretation.o.Build()
		rel.R.Tasks = append(rel.R.Tasks, o)
		o.AiInterpretationID = null.From(rel.ID) // h2
		o.R.AiInterpretation = rel
	}

	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.Tasks = append(rel.R.Tasks, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.TaskSetter
// this does nothing with the relationship templates
func (o TaskTemplate) BuildSetter() *models.TaskSetter {
	m := &models.TaskSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Title != nil {
		val := o.Title()
		m.Title = omit.From(val)
	}
	if o.Description != nil {
		val := o.Description()
		m.Description = omitnull.FromNull(val)
	}
	if o.DueAt != nil {
		val := o.DueAt()
		m.DueAt = omitnull.FromNull(val)
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = omit.From(val)
	}
	if o.Source != nil {
		val := o.Source()
		m.Source = omit.From(val)
	}
	if o.AiInterpretationID != nil {
		val := o.AiInterpretationID()
		m.AiInterpretationID = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.TaskSetter
// this does nothing with the relationship templates
func (o TaskTemplate) BuildManySetter(number int) []*models.TaskSetter {
	m := make([]*models.TaskSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Task
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TaskTemplate.Create
func (o TaskTemplate) Build() *models.Task {
	m := &models.Task{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Title != nil {
		m.Title = o.Title()
	}
	if o.Description != nil {
		m.Description = o.Description()
	}
	if o.DueAt != nil {
		m.DueAt = o.DueAt()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.Source != nil {
		m.Source = o.Source()
	}
	if o.AiInterpretationID != nil {
		m.AiInterpretationID = o.AiInterpretationID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.TaskSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TaskTemplate.CreateMany
func (o TaskTemplate) BuildMany(number int) models.TaskSlice {
	m := make(models.TaskSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableTask(m *models.TaskSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "36")
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil, "36")
		m.UserID = omit.From(val)
	}
	if !(m.Title.IsValue()) {
		val := random_string(nil, "500")
		m.Title = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Task
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *TaskTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Task) error {
	var err error

	isAiInterpretationDone, _ := taskRelAiInterpretationCtx.Value(ctx)
	if !isAiInterpretationDone && o.r.AiInterpretation != nil {
		ctx = taskRelAiInterpretationCtx.WithValue(ctx, true)
		if o.r.AiInterpretation.o.alreadyPersisted {
			m.R.AiInterpretation = o.r.AiInterpretation.o.Build()
		} else {
			var rel0 *models.AiInterpretation
			rel0, err = o.r.AiInterpretation.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachAiInterpretation(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a task and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *TaskTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Task, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableTask(opt)

	if o.r.User == nil {
		TaskMods.WithNewUser().Apply(ctx, o)
	}

	var rel1 *models.User

	if o.r.User.o.alreadyPersisted {
		rel1 = o.r.User.o.Build()
	} else {
		rel1, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel1.ID)

	m, err := models.Tasks.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a task and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *TaskTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Task {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a task and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *TaskTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Task {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple tasks and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o TaskTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.TaskSlice, error) {
	var err error
	m := make(models.TaskSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple tasks and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o TaskTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.TaskSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple tasks and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o TaskTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.TaskSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Task has methods that act as mods for the TaskTemplate
var TaskMods taskMods

type taskMods struct{}

func (m taskMods) RandomizeAllColumns(f *faker.Faker) TaskMod {
	return TaskModSlice{
		TaskMods.RandomID(f),
		TaskMods.RandomUserID(f),
		TaskMods.RandomTitle(f),
		TaskMods.RandomDescription(f),
		TaskMods.RandomDueAt(f),
		TaskMods.RandomStatus(f),
		TaskMods.RandomSource(f),
		TaskMods.RandomAiInterpretationID(f),
		TaskMods.RandomCreatedAt(f),
		TaskMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m taskMods) ID(val string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m taskMods) IDFunc(f func() string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetID() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomID(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.ID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m taskMods) UserID(val string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m taskMods) UserIDFunc(f func() string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetUserID() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomUserID(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UserID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m taskMods) Title(val string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Title = func() string { return val }
	})
}

// Set the Column from the function
func (m taskMods) TitleFunc(f func() string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Title = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetTitle() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Title = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomTitle(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Title = func() string {
			return random_string(f, "500")
		}
	})
}

// Set the model columns to this value
func (m taskMods) Description(val null.Val[string]) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Description = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m taskMods) DescriptionFunc(f func() null.Val[string]) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Description = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetDescription() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Description = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m taskMods) RandomDescription(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m taskMods) RandomDescriptionNotNull(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Description = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m taskMods) DueAt(val null.Val[time.Time]) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.DueAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m taskMods) DueAtFunc(f func() null.Val[time.Time]) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.DueAt = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetDueAt() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.DueAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m taskMods) RandomDueAt(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.DueAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m taskMods) RandomDueAtNotNull(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.DueAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m taskMods) Status(val string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m taskMods) StatusFunc(f func() string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetStatus() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomStatus(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Status = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m taskMods) Source(val string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Source = func() string { return val }
	})
}

// Set the Column from the function
func (m taskMods) SourceFunc(f func() string) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Source = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetSource() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Source = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomSource(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.Source = func() string {
			return random_string(f, "20")
		}
	})
}

// Set the model columns to this value
func (m taskMods) AiInterpretationID(val null.Val[string]) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.AiInterpretationID = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m taskMods) AiInterpretationIDFunc(f func() null.Val[string]) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.AiInterpretationID = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetAiInterpretationID() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.AiInterpretationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m taskMods) RandomAiInterpretationID(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.AiInterpretationID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "36")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m taskMods) RandomAiInterpretationIDNotNull(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.AiInterpretationID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "36")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m taskMods) CreatedAt(val time.Time) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m taskMods) CreatedAtFunc(f func() time.Time) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetCreatedAt() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomCreatedAt(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m taskMods) UpdatedAt(val time.Time) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m taskMods) UpdatedAtFunc(f func() time.Time) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m taskMods) UnsetUpdatedAt() TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskMods) RandomUpdatedAt(f *faker.Faker) TaskMod {
	return TaskModFunc(func(_ context.Context, o *TaskTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m taskMods) WithParentsCascading() TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		if isDone, _ := taskWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = taskWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewAiInterpretationWithContext(ctx, AiInterpretationMods.WithParentsCascading())
			m.WithAiInterpretation(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m taskMods) WithAiInterpretation(rel *AiInterpretationTemplate) TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		o.r.AiInterpretation = &taskRAiInterpretationR{
			o: rel,
		}
	})
}

func (m taskMods) WithNewAiInterpretation(mods ...AiInterpretationMod) TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		related := o.f.NewAiInterpretationWithContext(ctx, mods...)

		m.WithAiInterpretation(related).Apply(ctx, o)
	})
}

func (m taskMods) WithExistingAiInterpretation(em *models.AiInterpretation) TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		o.r.AiInterpretation = &taskRAiInterpretationR{
			o: o.f.FromExistingAiInterpretation(em),
		}
	})
}

func (m taskMods) WithoutAiInterpretation() TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		o.r.AiInterpretation = nil
	})
}

func (m taskMods) WithUser(rel *UserTemplate) TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		o.r.User = &taskRUserR{
			o: rel,
		}
	})
}

func (m taskMods) WithNewUser(mods ...UserMod) TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m taskMods) WithExistingUser(em *models.User) TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		o.r.User = &taskRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m taskMods) WithoutUser() TaskMod {
	return TaskModFunc(func(ctx context.Context, o *TaskTemplate) {
		o.r.User = nil
	})
}
