// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "github.com/yoshioka0101/ai_plan_chat/models"
)

type UserMod interface {
	Apply(context.Context, *UserTemplate)
}

type UserModFunc func(context.Context, *UserTemplate)

func (f UserModFunc) Apply(ctx context.Context, n *UserTemplate) {
	f(ctx, n)
}

type UserModSlice []UserMod

func (mods UserModSlice) Apply(ctx context.Context, n *UserTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserTemplate struct {
	ID        func() string
	GoogleID  func() string
	Email     func() string
	Nickname  func() string
	Avatar    func() null.Val[string]
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r userR
	f *Factory

	alreadyPersisted bool
}

type userR struct {
	AiInterpretations []*userRAiInterpretationsR
	Tasks             []*userRTasksR
	UserAuths         []*userRUserAuthsR
}

type userRAiInterpretationsR struct {
	number int
	o      *AiInterpretationTemplate
}
type userRTasksR struct {
	number int
	o      *TaskTemplate
}
type userRUserAuthsR struct {
	number int
	o      *UserAuthTemplate
}

// Apply mods to the UserTemplate
func (o *UserTemplate) Apply(ctx context.Context, mods ...UserMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.User
// according to the relationships in the template. Nothing is inserted into the db
func (t UserTemplate) setModelRels(o *models.User) {
	if t.r.AiInterpretations != nil {
		rel := models.AiInterpretationSlice{}
		for _, r := range t.r.AiInterpretations {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.AiInterpretations = rel
	}

	if t.r.Tasks != nil {
		rel := models.TaskSlice{}
		for _, r := range t.r.Tasks {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.Tasks = rel
	}

	if t.r.UserAuths != nil {
		rel := models.UserAuthSlice{}
		for _, r := range t.r.UserAuths {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
				rel.R.User = o
			}
			rel = append(rel, related...)
		}
		o.R.UserAuths = rel
	}
}

// BuildSetter returns an *models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildSetter() *models.UserSetter {
	m := &models.UserSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.GoogleID != nil {
		val := o.GoogleID()
		m.GoogleID = omit.From(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.Nickname != nil {
		val := o.Nickname()
		m.Nickname = omit.From(val)
	}
	if o.Avatar != nil {
		val := o.Avatar()
		m.Avatar = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildManySetter(number int) []*models.UserSetter {
	m := make([]*models.UserSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.User
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.Create
func (o UserTemplate) Build() *models.User {
	m := &models.User{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.GoogleID != nil {
		m.GoogleID = o.GoogleID()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Nickname != nil {
		m.Nickname = o.Nickname()
	}
	if o.Avatar != nil {
		m.Avatar = o.Avatar()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.CreateMany
func (o UserTemplate) BuildMany(number int) models.UserSlice {
	m := make(models.UserSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUser(m *models.UserSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "36")
		m.ID = omit.From(val)
	}
	if !(m.GoogleID.IsValue()) {
		val := random_string(nil, "255")
		m.GoogleID = omit.From(val)
	}
	if !(m.Email.IsValue()) {
		val := random_string(nil, "255")
		m.Email = omit.From(val)
	}
	if !(m.Nickname.IsValue()) {
		val := random_string(nil, "100")
		m.Nickname = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.User
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.User) error {
	var err error

	isAiInterpretationsDone, _ := userRelAiInterpretationsCtx.Value(ctx)
	if !isAiInterpretationsDone && o.r.AiInterpretations != nil {
		ctx = userRelAiInterpretationsCtx.WithValue(ctx, true)
		for _, r := range o.r.AiInterpretations {
			if r.o.alreadyPersisted {
				m.R.AiInterpretations = append(m.R.AiInterpretations, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachAiInterpretations(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isTasksDone, _ := userRelTasksCtx.Value(ctx)
	if !isTasksDone && o.r.Tasks != nil {
		ctx = userRelTasksCtx.WithValue(ctx, true)
		for _, r := range o.r.Tasks {
			if r.o.alreadyPersisted {
				m.R.Tasks = append(m.R.Tasks, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachTasks(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isUserAuthsDone, _ := userRelUserAuthsCtx.Value(ctx)
	if !isUserAuthsDone && o.r.UserAuths != nil {
		ctx = userRelUserAuthsCtx.WithValue(ctx, true)
		for _, r := range o.r.UserAuths {
			if r.o.alreadyPersisted {
				m.R.UserAuths = append(m.R.UserAuths, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUserAuths(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserTemplate) Create(ctx context.Context, exec bob.Executor) (*models.User, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUser(opt)

	m, err := models.Users.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.User {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.User {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserSlice, error) {
	var err error
	m := make(models.UserSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// User has methods that act as mods for the UserTemplate
var UserMods userMods

type userMods struct{}

func (m userMods) RandomizeAllColumns(f *faker.Faker) UserMod {
	return UserModSlice{
		UserMods.RandomID(f),
		UserMods.RandomGoogleID(f),
		UserMods.RandomEmail(f),
		UserMods.RandomNickname(f),
		UserMods.RandomAvatar(f),
		UserMods.RandomCreatedAt(f),
		UserMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m userMods) ID(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) IDFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m userMods) UnsetID() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomID(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m userMods) GoogleID(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GoogleID = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) GoogleIDFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GoogleID = f
	})
}

// Clear any values for the column
func (m userMods) UnsetGoogleID() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GoogleID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomGoogleID(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GoogleID = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m userMods) Email(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) EmailFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m userMods) UnsetEmail() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomEmail(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m userMods) Nickname(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Nickname = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) NicknameFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Nickname = f
	})
}

// Clear any values for the column
func (m userMods) UnsetNickname() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Nickname = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomNickname(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Nickname = func() string {
			return random_string(f, "100")
		}
	})
}

// Set the model columns to this value
func (m userMods) Avatar(val null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Avatar = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userMods) AvatarFunc(f func() null.Val[string]) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Avatar = f
	})
}

// Clear any values for the column
func (m userMods) UnsetAvatar() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Avatar = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userMods) RandomAvatar(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Avatar = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "500")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userMods) RandomAvatarNotNull(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Avatar = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "500")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userMods) CreatedAt(val time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userMods) CreatedAtFunc(f func() time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetCreatedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomCreatedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) UpdatedAt(val time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userMods) UpdatedAtFunc(f func() time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetUpdatedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomUpdatedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m userMods) WithParentsCascading() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		if isDone, _ := userWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m userMods) WithAiInterpretations(number int, related *AiInterpretationTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.AiInterpretations = []*userRAiInterpretationsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewAiInterpretations(number int, mods ...AiInterpretationMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewAiInterpretationWithContext(ctx, mods...)
		m.WithAiInterpretations(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddAiInterpretations(number int, related *AiInterpretationTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.AiInterpretations = append(o.r.AiInterpretations, &userRAiInterpretationsR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewAiInterpretations(number int, mods ...AiInterpretationMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewAiInterpretationWithContext(ctx, mods...)
		m.AddAiInterpretations(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingAiInterpretations(existingModels ...*models.AiInterpretation) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.AiInterpretations = append(o.r.AiInterpretations, &userRAiInterpretationsR{
				o: o.f.FromExistingAiInterpretation(em),
			})
		}
	})
}

func (m userMods) WithoutAiInterpretations() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.AiInterpretations = nil
	})
}

func (m userMods) WithTasks(number int, related *TaskTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Tasks = []*userRTasksR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewTasks(number int, mods ...TaskMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewTaskWithContext(ctx, mods...)
		m.WithTasks(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddTasks(number int, related *TaskTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Tasks = append(o.r.Tasks, &userRTasksR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewTasks(number int, mods ...TaskMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewTaskWithContext(ctx, mods...)
		m.AddTasks(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingTasks(existingModels ...*models.Task) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.Tasks = append(o.r.Tasks, &userRTasksR{
				o: o.f.FromExistingTask(em),
			})
		}
	})
}

func (m userMods) WithoutTasks() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Tasks = nil
	})
}

func (m userMods) WithUserAuths(number int, related *UserAuthTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.UserAuths = []*userRUserAuthsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewUserAuths(number int, mods ...UserAuthMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserAuthWithContext(ctx, mods...)
		m.WithUserAuths(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddUserAuths(number int, related *UserAuthTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.UserAuths = append(o.r.UserAuths, &userRUserAuthsR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewUserAuths(number int, mods ...UserAuthMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewUserAuthWithContext(ctx, mods...)
		m.AddUserAuths(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingUserAuths(existingModels ...*models.UserAuth) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.UserAuths = append(o.r.UserAuths, &userRUserAuthsR{
				o: o.f.FromExistingUserAuth(em),
			})
		}
	})
}

func (m userMods) WithoutUserAuths() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.UserAuths = nil
	})
}
