// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "github.com/yoshioka0101/ai_plan_chat/models"
)

type UserAuthMod interface {
	Apply(context.Context, *UserAuthTemplate)
}

type UserAuthModFunc func(context.Context, *UserAuthTemplate)

func (f UserAuthModFunc) Apply(ctx context.Context, n *UserAuthTemplate) {
	f(ctx, n)
}

type UserAuthModSlice []UserAuthMod

func (mods UserAuthModSlice) Apply(ctx context.Context, n *UserAuthTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserAuthTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserAuthTemplate struct {
	ID           func() string
	UserID       func() string
	IdentityType func() string
	Identifier   func() string
	Credential   func() null.Val[string]
	CreatedAt    func() time.Time
	UpdatedAt    func() time.Time

	r userAuthR
	f *Factory

	alreadyPersisted bool
}

type userAuthR struct {
	User *userAuthRUserR
}

type userAuthRUserR struct {
	o *UserTemplate
}

// Apply mods to the UserAuthTemplate
func (o *UserAuthTemplate) Apply(ctx context.Context, mods ...UserAuthMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.UserAuth
// according to the relationships in the template. Nothing is inserted into the db
func (t UserAuthTemplate) setModelRels(o *models.UserAuth) {
	if t.r.User != nil {
		rel := t.r.User.o.Build()
		rel.R.UserAuths = append(rel.R.UserAuths, o)
		o.UserID = rel.ID // h2
		o.R.User = rel
	}
}

// BuildSetter returns an *models.UserAuthSetter
// this does nothing with the relationship templates
func (o UserAuthTemplate) BuildSetter() *models.UserAuthSetter {
	m := &models.UserAuthSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.IdentityType != nil {
		val := o.IdentityType()
		m.IdentityType = omit.From(val)
	}
	if o.Identifier != nil {
		val := o.Identifier()
		m.Identifier = omit.From(val)
	}
	if o.Credential != nil {
		val := o.Credential()
		m.Credential = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.UserAuthSetter
// this does nothing with the relationship templates
func (o UserAuthTemplate) BuildManySetter(number int) []*models.UserAuthSetter {
	m := make([]*models.UserAuthSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.UserAuth
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserAuthTemplate.Create
func (o UserAuthTemplate) Build() *models.UserAuth {
	m := &models.UserAuth{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.IdentityType != nil {
		m.IdentityType = o.IdentityType()
	}
	if o.Identifier != nil {
		m.Identifier = o.Identifier()
	}
	if o.Credential != nil {
		m.Credential = o.Credential()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserAuthSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserAuthTemplate.CreateMany
func (o UserAuthTemplate) BuildMany(number int) models.UserAuthSlice {
	m := make(models.UserAuthSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUserAuth(m *models.UserAuthSetter) {
	if !(m.ID.IsValue()) {
		val := random_string(nil, "36")
		m.ID = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_string(nil, "36")
		m.UserID = omit.From(val)
	}
	if !(m.IdentityType.IsValue()) {
		val := random_string(nil, "50")
		m.IdentityType = omit.From(val)
	}
	if !(m.Identifier.IsValue()) {
		val := random_string(nil, "255")
		m.Identifier = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.UserAuth
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserAuthTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.UserAuth) error {
	var err error

	return err
}

// Create builds a userAuth and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserAuthTemplate) Create(ctx context.Context, exec bob.Executor) (*models.UserAuth, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUserAuth(opt)

	if o.r.User == nil {
		UserAuthMods.WithNewUser().Apply(ctx, o)
	}

	var rel0 *models.User

	if o.r.User.o.alreadyPersisted {
		rel0 = o.r.User.o.Build()
	} else {
		rel0, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.UserAuths.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a userAuth and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserAuthTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.UserAuth {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a userAuth and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserAuthTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.UserAuth {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple userAuths and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserAuthTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserAuthSlice, error) {
	var err error
	m := make(models.UserAuthSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple userAuths and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserAuthTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserAuthSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple userAuths and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserAuthTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserAuthSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// UserAuth has methods that act as mods for the UserAuthTemplate
var UserAuthMods userAuthMods

type userAuthMods struct{}

func (m userAuthMods) RandomizeAllColumns(f *faker.Faker) UserAuthMod {
	return UserAuthModSlice{
		UserAuthMods.RandomID(f),
		UserAuthMods.RandomUserID(f),
		UserAuthMods.RandomIdentityType(f),
		UserAuthMods.RandomIdentifier(f),
		UserAuthMods.RandomCredential(f),
		UserAuthMods.RandomCreatedAt(f),
		UserAuthMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m userAuthMods) ID(val string) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m userAuthMods) IDFunc(f func() string) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m userAuthMods) UnsetID() UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAuthMods) RandomID(f *faker.Faker) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.ID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m userAuthMods) UserID(val string) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.UserID = func() string { return val }
	})
}

// Set the Column from the function
func (m userAuthMods) UserIDFunc(f func() string) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m userAuthMods) UnsetUserID() UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAuthMods) RandomUserID(f *faker.Faker) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.UserID = func() string {
			return random_string(f, "36")
		}
	})
}

// Set the model columns to this value
func (m userAuthMods) IdentityType(val string) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.IdentityType = func() string { return val }
	})
}

// Set the Column from the function
func (m userAuthMods) IdentityTypeFunc(f func() string) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.IdentityType = f
	})
}

// Clear any values for the column
func (m userAuthMods) UnsetIdentityType() UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.IdentityType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAuthMods) RandomIdentityType(f *faker.Faker) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.IdentityType = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m userAuthMods) Identifier(val string) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.Identifier = func() string { return val }
	})
}

// Set the Column from the function
func (m userAuthMods) IdentifierFunc(f func() string) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.Identifier = f
	})
}

// Clear any values for the column
func (m userAuthMods) UnsetIdentifier() UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.Identifier = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAuthMods) RandomIdentifier(f *faker.Faker) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.Identifier = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m userAuthMods) Credential(val null.Val[string]) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.Credential = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m userAuthMods) CredentialFunc(f func() null.Val[string]) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.Credential = f
	})
}

// Clear any values for the column
func (m userAuthMods) UnsetCredential() UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.Credential = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userAuthMods) RandomCredential(f *faker.Faker) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.Credential = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userAuthMods) RandomCredentialNotNull(f *faker.Faker) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.Credential = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userAuthMods) CreatedAt(val time.Time) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userAuthMods) CreatedAtFunc(f func() time.Time) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m userAuthMods) UnsetCreatedAt() UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAuthMods) RandomCreatedAt(f *faker.Faker) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m userAuthMods) UpdatedAt(val time.Time) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userAuthMods) UpdatedAtFunc(f func() time.Time) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m userAuthMods) UnsetUpdatedAt() UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAuthMods) RandomUpdatedAt(f *faker.Faker) UserAuthMod {
	return UserAuthModFunc(func(_ context.Context, o *UserAuthTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m userAuthMods) WithParentsCascading() UserAuthMod {
	return UserAuthModFunc(func(ctx context.Context, o *UserAuthTemplate) {
		if isDone, _ := userAuthWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userAuthWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m userAuthMods) WithUser(rel *UserTemplate) UserAuthMod {
	return UserAuthModFunc(func(ctx context.Context, o *UserAuthTemplate) {
		o.r.User = &userAuthRUserR{
			o: rel,
		}
	})
}

func (m userAuthMods) WithNewUser(mods ...UserMod) UserAuthMod {
	return UserAuthModFunc(func(ctx context.Context, o *UserAuthTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m userAuthMods) WithExistingUser(em *models.User) UserAuthMod {
	return UserAuthModFunc(func(ctx context.Context, o *UserAuthTemplate) {
		o.r.User = &userAuthRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m userAuthMods) WithoutUser() UserAuthMod {
	return UserAuthModFunc(func(ctx context.Context, o *UserAuthTemplate) {
		o.r.User = nil
	})
}
