// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var AiInterpretations = Table[
	aiInterpretationColumns,
	aiInterpretationIndexes,
	aiInterpretationForeignKeys,
	aiInterpretationUniques,
	aiInterpretationChecks,
]{
	Schema: "",
	Name:   "ai_interpretations",
	Columns: aiInterpretationColumns{
		ID: column{
			Name:      "id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "AI解釈ID (UUID)",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "ユーザーID",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InputText: column{
			Name:      "input_text",
			DBType:    "text",
			Default:   "",
			Comment:   "ユーザーが入力した自然言語テキスト",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StructuredResult: column{
			Name:      "structured_result",
			DBType:    "json",
			Default:   "",
			Comment:   "AI解析結果のJSON構造",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AiModel: column{
			Name:      "ai_model",
			DBType:    "varchar(100)",
			Default:   "gemini-flash",
			Comment:   "使用AIモデル名",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "解析実行日時",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: aiInterpretationIndexes{
		IdxAiInterpretationsType: index{
			Type: "BTREE",
			Name: "idx_ai_interpretations_type",
			Columns: []indexColumn{
				{
					Name:         "cast(json_unquote(json_extract(`structured_result`,_utf8mb4\\'$.type\\')) as char(50) charset utf8mb4)",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxAiInterpretationsUserCreated: index{
			Type: "BTREE",
			Name: "idx_ai_interpretations_user_created",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "created_at",
					Desc:         null.FromCond(true, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: aiInterpretationForeignKeys{
		FKAiInterpretationsUser: foreignKey{
			constraint: constraint{
				Name:    "fk_ai_interpretations_user",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "AI解析履歴",
}

type aiInterpretationColumns struct {
	ID               column
	UserID           column
	InputText        column
	StructuredResult column
	AiModel          column
	CreatedAt        column
}

func (c aiInterpretationColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.InputText, c.StructuredResult, c.AiModel, c.CreatedAt,
	}
}

type aiInterpretationIndexes struct {
	IdxAiInterpretationsType        index
	IdxAiInterpretationsUserCreated index
	PRIMARY                         index
}

func (i aiInterpretationIndexes) AsSlice() []index {
	return []index{
		i.IdxAiInterpretationsType, i.IdxAiInterpretationsUserCreated, i.PRIMARY,
	}
}

type aiInterpretationForeignKeys struct {
	FKAiInterpretationsUser foreignKey
}

func (f aiInterpretationForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKAiInterpretationsUser,
	}
}

type aiInterpretationUniques struct{}

func (u aiInterpretationUniques) AsSlice() []constraint {
	return []constraint{}
}

type aiInterpretationChecks struct{}

func (c aiInterpretationChecks) AsSlice() []check {
	return []check{}
}
