// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var InterpretationItems = Table[
	interpretationItemColumns,
	interpretationItemIndexes,
	interpretationItemForeignKeys,
	interpretationItemUniques,
	interpretationItemChecks,
]{
	Schema: "",
	Name:   "interpretation_items",
	Columns: interpretationItemColumns{
		ID: column{
			Name:      "id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "アイテムID (UUID)",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InterpretationID: column{
			Name:      "interpretation_id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "AI解釈ID",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ItemIndex: column{
			Name:      "item_index",
			DBType:    "int",
			Default:   "",
			Comment:   "結果内のindex",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ResourceType: column{
			Name:      "resource_type",
			DBType:    "varchar(20)",
			Default:   "",
			Comment:   "リソースタイプ (task/event/wallet)",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ResourceID: column{
			Name:      "resource_id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "作成済みリソースID",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "varchar(20)",
			Default:   "pending",
			Comment:   "ステータス (pending/created)",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Data: column{
			Name:      "data",
			DBType:    "json",
			Default:   "",
			Comment:   "編集後のアイテム内容",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OriginalData: column{
			Name:      "original_data",
			DBType:    "json",
			Default:   "",
			Comment:   "AI提案の原本",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ReviewedAt: column{
			Name:      "reviewed_at",
			DBType:    "timestamp",
			Default:   "",
			Comment:   "レビュー日時",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "作成日時",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "更新日時",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: interpretationItemIndexes{
		IdxInterpretationItemsInterpretation: index{
			Type: "BTREE",
			Name: "idx_interpretation_items_interpretation",
			Columns: []indexColumn{
				{
					Name:         "interpretation_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "item_index",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxInterpretationItemsResource: index{
			Type: "BTREE",
			Name: "idx_interpretation_items_resource",
			Columns: []indexColumn{
				{
					Name:         "resource_type",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "resource_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxInterpretationItemsStatus: index{
			Type: "BTREE",
			Name: "idx_interpretation_items_status",
			Columns: []indexColumn{
				{
					Name:         "interpretation_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "status",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: interpretationItemForeignKeys{
		FKInterpretationItemsInterpretation: foreignKey{
			constraint: constraint{
				Name:    "fk_interpretation_items_interpretation",
				Columns: []string{"interpretation_id"},
				Comment: "",
			},
			ForeignTable:   "ai_interpretations",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "AI解釈アイテム（レビュー対象）",
}

type interpretationItemColumns struct {
	ID               column
	InterpretationID column
	ItemIndex        column
	ResourceType     column
	ResourceID       column
	Status           column
	Data             column
	OriginalData     column
	ReviewedAt       column
	CreatedAt        column
	UpdatedAt        column
}

func (c interpretationItemColumns) AsSlice() []column {
	return []column{
		c.ID, c.InterpretationID, c.ItemIndex, c.ResourceType, c.ResourceID, c.Status, c.Data, c.OriginalData, c.ReviewedAt, c.CreatedAt, c.UpdatedAt,
	}
}

type interpretationItemIndexes struct {
	IdxInterpretationItemsInterpretation index
	IdxInterpretationItemsResource       index
	IdxInterpretationItemsStatus         index
	PRIMARY                              index
}

func (i interpretationItemIndexes) AsSlice() []index {
	return []index{
		i.IdxInterpretationItemsInterpretation, i.IdxInterpretationItemsResource, i.IdxInterpretationItemsStatus, i.PRIMARY,
	}
}

type interpretationItemForeignKeys struct {
	FKInterpretationItemsInterpretation foreignKey
}

func (f interpretationItemForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKInterpretationItemsInterpretation,
	}
}

type interpretationItemUniques struct{}

func (u interpretationItemUniques) AsSlice() []constraint {
	return []constraint{}
}

type interpretationItemChecks struct{}

func (c interpretationItemChecks) AsSlice() []check {
	return []check{}
}
