// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Tasks = Table[
	taskColumns,
	taskIndexes,
	taskForeignKeys,
	taskUniques,
	taskChecks,
]{
	Schema: "",
	Name:   "tasks",
	Columns: taskColumns{
		ID: column{
			Name:      "id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "タスクID (UUID)",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "ãƒ¦ãƒ¼ã‚¶ãƒ¼ID",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "varchar(500)",
			Default:   "",
			Comment:   "タスクタイトル",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "text",
			Default:   "",
			Comment:   "タスク詳細",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DueAt: column{
			Name:      "due_at",
			DBType:    "timestamp",
			Default:   "",
			Comment:   "期限日時",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "varchar(20)",
			Default:   "todo",
			Comment:   "ステータス（pending/in_progress/completed）",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Source: column{
			Name:      "source",
			DBType:    "varchar(20)",
			Default:   "manual",
			Comment:   "ä½œæˆ\u0090å…ƒ",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AiInterpretationID: column{
			Name:      "ai_interpretation_id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "å…ƒã\u0081®AIè§£é‡ˆID",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "作成日時",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "更新日時",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: taskIndexes{
		FKTasksAiInterpretation: index{
			Type: "BTREE",
			Name: "fk_tasks_ai_interpretation",
			Columns: []indexColumn{
				{
					Name:         "ai_interpretation_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxTasksCreatedAt: index{
			Type: "BTREE",
			Name: "idx_tasks_created_at",
			Columns: []indexColumn{
				{
					Name:         "created_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxTasksDueAt: index{
			Type: "BTREE",
			Name: "idx_tasks_due_at",
			Columns: []indexColumn{
				{
					Name:         "due_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxTasksStatus: index{
			Type: "BTREE",
			Name: "idx_tasks_status",
			Columns: []indexColumn{
				{
					Name:         "status",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxTasksUserCreated: index{
			Type: "BTREE",
			Name: "idx_tasks_user_created",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "created_at",
					Desc:         null.FromCond(true, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxTasksUserDue: index{
			Type: "BTREE",
			Name: "idx_tasks_user_due",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "due_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxTasksUserStatus: index{
			Type: "BTREE",
			Name: "idx_tasks_user_status",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "status",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: taskForeignKeys{
		FKTasksAiInterpretation: foreignKey{
			constraint: constraint{
				Name:    "fk_tasks_ai_interpretation",
				Columns: []string{"ai_interpretation_id"},
				Comment: "",
			},
			ForeignTable:   "ai_interpretations",
			ForeignColumns: []string{"id"},
		},
		FKTasksUser: foreignKey{
			constraint: constraint{
				Name:    "fk_tasks_user",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "タスク",
}

type taskColumns struct {
	ID                 column
	UserID             column
	Title              column
	Description        column
	DueAt              column
	Status             column
	Source             column
	AiInterpretationID column
	CreatedAt          column
	UpdatedAt          column
}

func (c taskColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Title, c.Description, c.DueAt, c.Status, c.Source, c.AiInterpretationID, c.CreatedAt, c.UpdatedAt,
	}
}

type taskIndexes struct {
	FKTasksAiInterpretation index
	IdxTasksCreatedAt       index
	IdxTasksDueAt           index
	IdxTasksStatus          index
	IdxTasksUserCreated     index
	IdxTasksUserDue         index
	IdxTasksUserStatus      index
	PRIMARY                 index
}

func (i taskIndexes) AsSlice() []index {
	return []index{
		i.FKTasksAiInterpretation, i.IdxTasksCreatedAt, i.IdxTasksDueAt, i.IdxTasksStatus, i.IdxTasksUserCreated, i.IdxTasksUserDue, i.IdxTasksUserStatus, i.PRIMARY,
	}
}

type taskForeignKeys struct {
	FKTasksAiInterpretation foreignKey
	FKTasksUser             foreignKey
}

func (f taskForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKTasksAiInterpretation, f.FKTasksUser,
	}
}

type taskUniques struct{}

func (u taskUniques) AsSlice() []constraint {
	return []constraint{}
}

type taskChecks struct{}

func (c taskChecks) AsSlice() []check {
	return []check{}
}
