// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Tasks = Table[
	taskColumns,
	taskIndexes,
	taskForeignKeys,
	taskUniques,
	taskChecks,
]{
	Schema: "",
	Name:   "tasks",
	Columns: taskColumns{
		ID: column{
			Name:      "id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "タスクID (UUID)",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "varchar(500)",
			Default:   "",
			Comment:   "タスクタイトル",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "text",
			Default:   "",
			Comment:   "タスク詳細",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DueAt: column{
			Name:      "due_at",
			DBType:    "timestamp",
			Default:   "",
			Comment:   "期限日時",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "varchar(20)",
			Default:   "pending",
			Comment:   "ステータス（pending/in_progress/completed）",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "作成日時",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "更新日時",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: taskIndexes{
		IdxTasksCreatedAt: index{
			Type: "BTREE",
			Name: "idx_tasks_created_at",
			Columns: []indexColumn{
				{
					Name:         "created_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxTasksDueAt: index{
			Type: "BTREE",
			Name: "idx_tasks_due_at",
			Columns: []indexColumn{
				{
					Name:         "due_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxTasksStatus: index{
			Type: "BTREE",
			Name: "idx_tasks_status",
			Columns: []indexColumn{
				{
					Name:         "status",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "タスク",
}

type taskColumns struct {
	ID          column
	Title       column
	Description column
	DueAt       column
	Status      column
	CreatedAt   column
	UpdatedAt   column
}

func (c taskColumns) AsSlice() []column {
	return []column{
		c.ID, c.Title, c.Description, c.DueAt, c.Status, c.CreatedAt, c.UpdatedAt,
	}
}

type taskIndexes struct {
	IdxTasksCreatedAt index
	IdxTasksDueAt     index
	IdxTasksStatus    index
	PRIMARY           index
}

func (i taskIndexes) AsSlice() []index {
	return []index{
		i.IdxTasksCreatedAt, i.IdxTasksDueAt, i.IdxTasksStatus, i.PRIMARY,
	}
}

type taskForeignKeys struct{}

func (f taskForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type taskUniques struct{}

func (u taskUniques) AsSlice() []constraint {
	return []constraint{}
}

type taskChecks struct{}

func (c taskChecks) AsSlice() []check {
	return []check{}
}
