// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Users = Table[
	userColumns,
	userIndexes,
	userForeignKeys,
	userUniques,
	userChecks,
]{
	Schema: "",
	Name:   "users",
	Columns: userColumns{
		ID: column{
			Name:      "id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "ãƒ¦ãƒ¼ã‚¶ãƒ¼ID (UUID)",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GoogleID: column{
			Name:      "google_id",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "Googleãƒ¦ãƒ¼ã‚¶ãƒ¼ID",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Email: column{
			Name:      "email",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "ãƒ¡ãƒ¼ãƒ«ã‚¢ãƒ‰ãƒ¬ã‚¹",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Nickname: column{
			Name:      "nickname",
			DBType:    "varchar(100)",
			Default:   "",
			Comment:   "ãƒ‹ãƒƒã‚¯ãƒ\u008dãƒ¼ãƒ\u00a0/è¡¨ç¤ºå\u0090\u008d",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Avatar: column{
			Name:      "avatar",
			DBType:    "varchar(500)",
			Default:   "",
			Comment:   "ã‚¢ãƒ\u0090ã‚¿ãƒ¼ç”»åƒ\u008fURL",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "ä½œæˆ\u0090æ—¥æ™‚",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "æ›´æ–°æ—¥æ™‚",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userIndexes{
		IdxUsersCreatedAt: index{
			Type: "BTREE",
			Name: "idx_users_created_at",
			Columns: []indexColumn{
				{
					Name:         "created_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IdxUsersEmail: index{
			Type: "BTREE",
			Name: "idx_users_email",
			Columns: []indexColumn{
				{
					Name:         "email",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		IdxUsersGoogleID: index{
			Type: "BTREE",
			Name: "idx_users_google_id",
			Columns: []indexColumn{
				{
					Name:         "google_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: userUniques{
		IdxUsersEmail: constraint{
			Name:    "idx_users_email",
			Columns: []string{"email"},
			Comment: "",
		},
		IdxUsersGoogleID: constraint{
			Name:    "idx_users_google_id",
			Columns: []string{"google_id"},
			Comment: "",
		},
	},

	Comment: "ãƒ¦ãƒ¼ã‚¶ãƒ¼",
}

type userColumns struct {
	ID        column
	GoogleID  column
	Email     column
	Nickname  column
	Avatar    column
	CreatedAt column
	UpdatedAt column
}

func (c userColumns) AsSlice() []column {
	return []column{
		c.ID, c.GoogleID, c.Email, c.Nickname, c.Avatar, c.CreatedAt, c.UpdatedAt,
	}
}

type userIndexes struct {
	IdxUsersCreatedAt index
	IdxUsersEmail     index
	IdxUsersGoogleID  index
	PRIMARY           index
}

func (i userIndexes) AsSlice() []index {
	return []index{
		i.IdxUsersCreatedAt, i.IdxUsersEmail, i.IdxUsersGoogleID, i.PRIMARY,
	}
}

type userForeignKeys struct{}

func (f userForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type userUniques struct {
	IdxUsersEmail    constraint
	IdxUsersGoogleID constraint
}

func (u userUniques) AsSlice() []constraint {
	return []constraint{
		u.IdxUsersEmail, u.IdxUsersGoogleID,
	}
}

type userChecks struct{}

func (c userChecks) AsSlice() []check {
	return []check{}
}
