// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var UserAuths = Table[
	userAuthColumns,
	userAuthIndexes,
	userAuthForeignKeys,
	userAuthUniques,
	userAuthChecks,
]{
	Schema: "",
	Name:   "user_auths",
	Columns: userAuthColumns{
		ID: column{
			Name:      "id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "èª\u008dè¨¼ID (UUID)",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "char(36)",
			Default:   "",
			Comment:   "ãƒ¦ãƒ¼ã‚¶ãƒ¼ID",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IdentityType: column{
			Name:      "identity_type",
			DBType:    "varchar(50)",
			Default:   "",
			Comment:   "èª\u008dè¨¼ã‚¿ã‚¤ãƒ—ï¼ˆgoogle, email, githubç\u00ad‰ï¼‰",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Identifier: column{
			Name:      "identifier",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "è\u00ad˜åˆ¥å\u00ad\u0090ï¼ˆãƒ¡ãƒ¼ãƒ«ã‚¢ãƒ‰ãƒ¬ã‚¹ã€\u0081ãƒ¦ãƒ¼ã‚¶ãƒ¼å\u0090\u008dç\u00ad‰ï¼‰",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Credential: column{
			Name:      "credential",
			DBType:    "text",
			Default:   "",
			Comment:   "èª\u008dè¨¼æƒ…å\u00a0±ï¼ˆãƒˆãƒ¼ã‚¯ãƒ³ã€\u0081èª\u008dè¨¼ã‚³ãƒ¼ãƒ‰ç\u00ad‰ï¼‰",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "ä½œæˆ\u0090æ—¥æ™‚",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "æ›´æ–°æ—¥æ™‚",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userAuthIndexes{
		IdxUserAuthsIdentifier: index{
			Type: "BTREE",
			Name: "idx_user_auths_identifier",
			Columns: []indexColumn{
				{
					Name:         "identity_type",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "identifier",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		UkUserAuthsIdentity: index{
			Type: "BTREE",
			Name: "uk_user_auths_identity",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "identity_type",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "identifier",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: userAuthForeignKeys{
		FKUserAuthsUser: foreignKey{
			constraint: constraint{
				Name:    "fk_user_auths_user",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: userAuthUniques{
		UkUserAuthsIdentity: constraint{
			Name:    "uk_user_auths_identity",
			Columns: []string{"user_id", "identity_type", "identifier"},
			Comment: "",
		},
	},

	Comment: "ãƒ¦ãƒ¼ã‚¶ãƒ¼èª\u008dè¨¼æƒ…å\u00a0±",
}

type userAuthColumns struct {
	ID           column
	UserID       column
	IdentityType column
	Identifier   column
	Credential   column
	CreatedAt    column
	UpdatedAt    column
}

func (c userAuthColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.IdentityType, c.Identifier, c.Credential, c.CreatedAt, c.UpdatedAt,
	}
}

type userAuthIndexes struct {
	IdxUserAuthsIdentifier index
	PRIMARY                index
	UkUserAuthsIdentity    index
}

func (i userAuthIndexes) AsSlice() []index {
	return []index{
		i.IdxUserAuthsIdentifier, i.PRIMARY, i.UkUserAuthsIdentity,
	}
}

type userAuthForeignKeys struct {
	FKUserAuthsUser foreignKey
}

func (f userAuthForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKUserAuthsUser,
	}
}

type userAuthUniques struct {
	UkUserAuthsIdentity constraint
}

func (u userAuthUniques) AsSlice() []constraint {
	return []constraint{
		u.UkUserAuthsIdentity,
	}
}

type userAuthChecks struct{}

func (c userAuthChecks) AsSlice() []check {
	return []check{}
}
