root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/api"

  include_ext = ["go", "yaml", "toml"]
  exclude_dir = ["vendor", "tmp"]
  exclude_file = ["*.log"]
  stop_on_error = true

[log]
  color = true
  time = true
  main_only = true

[misc]
  clean_on_exit = true