// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var AiInterpretationErrors = &aiInterpretationErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "ai_interpretations",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type aiInterpretationErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
