// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var InterpretationItemErrors = &interpretationItemErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "interpretation_items",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type interpretationItemErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
