// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TaskErrors = &taskErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "tasks",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type taskErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
