// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserErrors = &userErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"id"},
		s:       "PRIMARY",
	},

	ErrUniqueIdxUsersEmail: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"email"},
		s:       "idx_users_email",
	},

	ErrUniqueIdxUsersGoogleId: &UniqueConstraintError{
		schema:  "",
		table:   "users",
		columns: []string{"google_id"},
		s:       "idx_users_google_id",
	},
}

type userErrors struct {
	ErrUniquePrimary *UniqueConstraintError

	ErrUniqueIdxUsersEmail *UniqueConstraintError

	ErrUniqueIdxUsersGoogleId *UniqueConstraintError
}
