// Code generated by BobGen mysql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserAuthErrors = &userAuthErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "user_auths",
		columns: []string{"id"},
		s:       "PRIMARY",
	},

	ErrUniqueUkUserAuthsIdentity: &UniqueConstraintError{
		schema:  "",
		table:   "user_auths",
		columns: []string{"user_id", "identity_type", "identifier"},
		s:       "uk_user_auths_identity",
	},
}

type userAuthErrors struct {
	ErrUniquePrimary *UniqueConstraintError

	ErrUniqueUkUserAuthsIdentity *UniqueConstraintError
}
